---
- name: Testing Ansible Lightspeed
  hosts: monitoring
  become: true

  tasks:

    - name: Create an user named asterix on active directory on windows server 2019
      ansible.windows.win_user:
        name: asterix
        password: "{{ _password_ }}"
        state: present
        groups:
          - Administrators
          
    - name: change the user group to Administrators
      ansible.windows.win_user_right:
        name: SeSystemEnvironmentPrivilege
        users:
          - Administrators

    - name: add linux user named santos
      ansible.windows.win_user:
        name: santos
        password: "{{ password }}"
        state: present
        groups:
          - Administrators
    
    
